apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-service-reader
  namespace: ingress-nginx
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
