apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-reader-binding
  namespace: ingress-nginx
subjects:
- kind: ServiceAccount
  name: ingress-reader
  namespace: ingress-nginx
roleRef:
  kind: Role
  name: ingress-service-reader
  apiGroup: rbac.authorization.k8s.io
